server:
  port: 8081
spring:
  application:
    name: CompanyService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

employee-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8082